config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :games, only: [:create, :index, :show, :destroy] do
    get "choose_language", to: "games#choose_language", as: :choose_language
    get "choose_level", to: "games#choose_level", as: :choose_level
    resources :user_games, only: [:create]
    resources :game_qcms, only: [:create]
    member do
      get "avatar"
    end
  end

  get "leaderboard", to: "pages#leaderboard"
  get "profile", to: "pages#profile"

  resources :user_games, only: [:show, :update] do
    get "answer", to: "user_games#answer"
  end

  # get "avatar_select/:game_id", to: "user_games#games"
  # patch '/user_games/:id', to: 'user_games#update', as: 'update_user_games'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :game_qcms, dependent: :destroy
  has_many :qcms, through: :game_qcms
  has_many :user_games, dependent: :destroy
  has_many :users, through: :user_games
  belongs_to :user
  scope :joignable, -> { where(status: 'joignable') }

  def winner
    user_games.order(score: :asc).map(&:user).first
  end
end

# STATUS :
# created : créée mais pas de qcms associées encore donc pas joignable
# joignable : joignable (des qcms associés)
# started : join par 2 personnes (2 users games associés)

app/models/game_qcm.rb
class GameQcm < ApplicationRecord
  belongs_to :game
  belongs_to :qcm

  after_create :update_game_status

  private

  def update_game_status
    game.update(status: "joignable")
  end
end

app/models/qcm.rb
class Qcm < ApplicationRecord
  has_many :game_qcms, dependent: :destroy
  has_many :games, through: :game_qcms

  LANGUAGES = ["HTML", "Ruby", "JavaScript"]
  LEVELS = [1, 2, 3]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_games, class_name: 'Game'
  has_many :user_games, dependent: :destroy
  has_many :joined_games, through: :user_games, source: :game
  scope :ranked, -> { sort_by { |user| -user.computed_score } }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def computed_score
    total = 0
    user_games.each do |game|
      total += game.score
    end
    return total
  end

  def highest_level
    joined_games.pluck(:level).map(&:to_i).max()
  end

  def self.ranked
    all.sort_by { |user| -user.computed_score }
  end

  def games
    Game.where(id: (created_games | joined_games).map(&:id))
  end

end

app/models/user_game.rb
class UserGame < ApplicationRecord
  belongs_to :user
  belongs_to :game

  after_save :update_game_status

  AVATAR_URL = ["Avatar1.png", "Avatar2.png", "Avatar3.png",
                "Avatar4.png","Avatar5.png","Avatar6.png","Avatar7.png",
                "Avatar8.png","Avatar9.png","Avatar10.png","Avatar11.png",
                "Avatar12.png","Avatar13.png","Avatar14.png","Avatar15.png","Avatar16.png"]
                
  private

  def update_game_status
    game.update(status: "started") if game.users.count == 2
  end

  def computed_score
    game_qcms.sum(&:score)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:pseudo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:pseudo])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/game_qcms_controller.rb
class GameQcmsController < ApplicationController
  def create
    @game = Game.find(params[:game_id])
    @game.update(level: params[:qcm][:level])

    @questions = Qcm.where(level: @game.level.to_i, language: @game.language)
    @questions.each do |question|
      GameQcm.create(game: @game, qcm: question)
    end
    redirect_to game_path(@game)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def create
    @game = Game.new
    @user_game = UserGame.new(user: current_user, game: @game)
    @game.update(name: "#{current_user.pseudo}'s game")
    @game.update(user: current_user)

    if @user_game.save
      redirect_to user_game_path(@user_game)
    else
      render "pages#home", notice: "Oops, Something went wrong, please try again !"
    end
  end

  def choose_language
    @game = Game.find(params[:game_id])
  end

  def choose_level
    @game = Game.find(params[:game_id])
    @game.update(language: params[:qcm][:languages])
  end

  def index
    @games = Game.joignable.where.not(user: current_user)
  end

  def avatar
    @game = Game.find(params[:id])
    @user_game = UserGame.create!(game: @game, user: current_user)
    redirect_to user_game_path(@user_game)
  end

  def show
    @game = Game.find(params[:id])
    @user_game = UserGame.find_by(game: @game, user: current_user)
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def leaderboard
    @users = User.all
  end

  def profile
    @games = current_user.games
  end
end

app/controllers/user_games_controller.rb
class UserGamesController < ApplicationController
  def create
    @user_game = UserGame.new(user_game_params)
    @user_game.user = current_user
  end

  def update
    @user_game = UserGame.find(params[:id])
    @user_game.update(user_game_params)

    if @user_game.save
      if @user_game.game.user_games.count == 2
        GameChannel.broadcast_to(
          @user_game.game,
          { user_joined: true }.to_json
        )
        redirect_to game_path(@user_game.game)
      else
        redirect_to game_choose_language_path(@user_game.game)
      end
    end
  end

  def show
    @user_game = UserGame.find(params[:id])
  end

  def answer
    @user_game = UserGame.find(params[:user_game_id])
    result = params[:result]

    @user_game.score += 10 * @user_game.game.level.to_i if result == "true"
    # le step nous donne l'index de la question à aller prendre
    @user_game.step += 1
    @user_game.save
    @game = @user_game.game

    GameChannel.broadcast_to(
      @user_game.game,
      { user_answered: render_to_string(partial: "games/progress_bar", locals: {game: @game}, formats: [:html]) }.to_json
    )

    # stocker la question suivante
    @qcm = @user_game.game.qcms[@user_game.step]

    respond_to do |format|
      if @user_game.step >= @user_game.game.qcms.count
        if @game.user_games.all? { |u| u.step >= 5 }
          @game.update(status: "finished")
          determine_loser_and_apply_effect(@game)
          GameChannel.broadcast_to(
            @user_game.game,
            { user_finished: render_to_string(partial: "games/result", locals: {user_game: @user_game, game: @game}, formats: [:html]) }.to_json
          )
        end
        format.json { render json: {
          html: render_to_string(partial: "games/result", locals: {user_game: @user_game, game: @game}, formats: [:html]) }
        }
      else
        format.json { render json: {
          html: render_to_string(partial: "games/question", locals: {qcm: @qcm }, formats: [:html]) }
        }
      end
    end
  end

  private

  def determine_loser_and_apply_effect(game)
    @user_games = game.user_games.sort_by(&:score)
    @loser = @user_games.first.user
    @winner = @user_games.last.user
    @loser.update!(ejected: true)
    @winner.update!(ejected: false)
  end

  def user_game_params
    params.require(:user_game).permit(:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/games/_languages.html.erb
<div class="bg-white rounded p-2 mx-2 badge-languages d-flex justify-content-between">
  <h6 class="me-3"><%= cat %></h6>
  <%= image_tag "#{cat}.png", class: 'languages' %>
</div>

app/views/games/_level.html.erb
<div id="card-level" class="bg-white rounded p-3 mx-2 badge-level d-flex flex-column justify-content-space-around">
    <h5 style="color: white !important;">Level <span class="text-color-2"<%= level %>><%= level %></span></h5>
  <div>
    <% if level == 1 %>
      <p style="color: white !important;">
  On y va Molo
  <i class="em em-baby_chick" aria-role="presentation" aria-label="BABY CHICK"></i>
</p>
    <% elsif level == 2 %>
    <p style="color: white !important;">
  Ça commence à chauffer
  <i class="em em-fire" aria-role="presentation" aria-label="FIRE"></i>
</p>
    <% else %>
    <p style="color: white !important;">
  Le code n'a plus de secret
  <i class="em em-crystal_ball" aria-role="presentation" aria-label="CRYSTAL BALL"></i>
</p>
    <% end %>
  </div>
</div>

app/views/games/_progress_bar.html.erb
<div data-game-target="progress" class="d-flex mx-auto w-100 align-items-center justify-content-center">
  <%# FIRST USER %>
  <%= image_tag game.user_games.first.avatar, class: "avatar-small" %>
  <div class="d-flex mx-3">
    <% ((game.user_games.first.score / 10)/game.level.to_i).times do %>
      <div class="px-3 py-2 bg-greeny"></div>
    <% end %>
    <% (5 - (game.user_games.first.score/10)/game.level.to_i).times do %>
      <div class="px-3 py-2 bg-secondary"></div>
    <% end %>
  </div>
  <%# SECOND USER %>
  <div class="d-flex mx-3">
    <% ((game.user_games.last.score/10)/game.level.to_i).times do %>
      <div class="px-3 py-2 bg-greeny"></div>
    <% end %>
    <% (5 - (game.user_games.last.score/10)/game.level.to_i).times do %>
      <div class="px-3 py-2 bg-secondary"></div>
    <% end %>
  </div>
  <%= image_tag game.user_games.last.avatar, class: "avatar-small" %>
</div>

app/views/games/_question.html.erb
<%= render "games/progress_bar", game: @game %>

<div data-controller="question">
  <div class="question-title" data-question-target="title">
    <%= qcm.question %>
  </div>

  <% answers = [qcm.answer_one, qcm.answer_two, qcm.answer_true].shuffle %>

  <% answers.each do |answer| %>
    <div class="question mt-2" data-question-target="question" data-action="click->swap#swap" data-correct="<%= answer == qcm.answer_true %>">
      <%= answer %>
    </div>
  <% end %>
</div>



<%# <script>
  document.addEventListener('DOMContentLoaded', () => {
    const questionTitle = document.querySelector('.question-title');
    const questions = document.querySelectorAll('.question');

    questions.forEach((question) => {
      question.style.opacity = '0';
      question.style.visibility = 'hidden';
    });

    const showQuestions = () => {
      questionTitle.classList.add('show');

      questions.forEach((question, index) => {
        setTimeout(() => {
          question.style.opacity = '1';
          question.style.visibility = 'visible';
        }, (index + 1) * 300);
      });
    };

    questionTitle.addEventListener('transitionend', showQuestions);

    setTimeout(() => {
      questionTitle.classList.add('show');
    }, 300);
  });
</script> %>




<%# <script>
  document.addEventListener('DOMContentLoaded', () => {
    const questionElements = document.querySelectorAll('.question');

    questionElements.forEach((questionElement) => {
      questionElement.addEventListener('click', () => {
        questionElements.forEach((element) => {
          element.classList.remove('selected');
          element.classList.remove('correct');
          element.classList.remove('incorrect');
        });

        questionElement.classList.add('selected');

        const isCorrect = questionElement.getAttribute('data-correct') === 'true';

        if (isCorrect) {
          questionElement.classList.add('correct');
        } else {
          questionElement.classList.add('incorrect');
        }
      });
    });
  });
</script> %>

app/views/games/_result.html.erb
<div class="container" data-game-target= "result">
  <h2 style="font-family: 'Press Start 2P', cursive; margin-top: 140px; color: white;">Your Score</h2>
  <div class="d-flex align-items-center justify-content-center mt-5">
    <% game.users.each do |user| %>
      <% if user.user_games.find_by(game: game).step < 5 %>
        <div class="d-flex align-items-center flex-column p-3 m-3">
          <p>Still waiting on your opponent!</p>
        </div>
      <% else %>
        <% if game.user_games.first.score == game.user_games.last.score %>
          <div class="d-flex flex-column align-items-center">
            <div class="d-flex align-items-center flex-column p-3 m-3">
              <div class="d-flex">
                <p class="mx-2"><%= user.pseudo %></p>
                <div class="avatar-container">
                  <%= image_tag user.user_games.find_by(game: game).avatar, class: "avatar-small mb-3 winner" %>
                </div>
              </div>
              <h4><%= user.user_games.find_by(game: game).score %> / <%= 10 * 5 * @game.level.to_i %></h4>
            </div>
            <div class="right-gif2-container">
              <%= image_tag asset_path("ken-sfa-win.gif"), alt: "Winner GIF", class: "gif-score" %>
            </div>
          </div>
        <% elsif user.ejected == true %>
          <div class="d-flex flex-column align-items-center">
            <div class="d-flex align-items-center flex-column p-3 m-3">
              <div class="d-flex">
                <p class="mx-2"><%= user.pseudo %></p>
                  <div class="avatar-container">
                    <%= image_tag user.user_games.find_by(game: game).avatar, class: "avatar-small mb-3 ejected" %>
                  </div>
              </div>
              <h4><%= user.user_games.find_by(game: game).score %> / <%= 10 * 5 * @game.level.to_i %></h4>
            </div>
            <div class="left-gif2-container">
              <%= image_tag asset_path("ryu-twist.gif"), alt: "Eject GIF", class: "gif-score" %>
            </div>
          </div>
        <% else %>
          <div class="d-flex flex-column align-items-center">
            <div class="d-flex align-items-center flex-column p-3 m-3">
              <div class="d-flex">
                <p class="mx-2"><%= user.pseudo %></p>
                <div class="avatar-container">
                  <%= image_tag user.user_games.find_by(game: game).avatar, class: "avatar-small mb-3 winner" %>
                </div>
              </div>
              <h4><%= user.user_games.find_by(game: game).score %> / <%= 10 * 5 * @game.level.to_i %></h4>
            </div>
            <div class="right-gif2-container">
              <%= image_tag asset_path("ken-sfa-win.gif"), alt: "Winner GIF", class: "gif-score" %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>



<script>
  setTimeout(() => {
    console.log(document.querySelector('.ejected'))
    document.querySelector('.ejected').style.opacity = "0";
  }, 2000);
</script>
<%# <%= javascript_include_tag 'score-animation' %>

app/views/games/choose_language.html.erb
<h1>Choose a language</h1>
<%= simple_form_for :qcm, url: game_choose_level_path(@game), html: { "data-controller": "selection" }, method: :get  do |f| %>
  <%= f.input :languages,
      as: :radio_buttons,
      legend_tag: false,
      label_method: lambda { |cat| render 'languages', cat: cat },
      label_html: {class: "px-0"},
      input_html: {class: 'category-selector', "data-selection-target": "radioButton", "data-action": "click->selection#change"},
      item_wrapper_class: 'category-item col-4',
      collection_wrapper_tag: 'div',
      collection_wrapper_class: 'category-wrapper',
      collection: Qcm::LANGUAGES %>
  <div class="align-button-center">
    <%= f.submit 'Select', class: "button create-button col-4 mb-3", "data-selection-target": "selectButton", disabled: true %>
  </div>
<% end %>
<div>
  <img src="<%= asset_path('test-3.gif') %>" alt="Gif 3" class="gif-language">
</div>

app/views/games/choose_level.html.erb
<h1>Choose a level</h1>
<%= simple_form_for :qcm, url: game_game_qcms_path(@game), method: :post, html: { id: 'level-form', "data-controller": "selection"  } do |f| %>
  <%= f.input :level,
      legend_tag: false,
      as: :radio_buttons,
      label_method: lambda { |level| render "level", level: level },
      collection_wrapper_tag: 'div',
      collection_wrapper_class: 'category-wrapper',
      item_wrapper_class: 'category-item col-4',
      input_html: {class: 'category-selector', "data-selection-target": "radioButton", "data-action": "click->selection#change"},
      collection: Qcm::LEVELS %>
  <div class="align-button-center">
    <%= f.submit 'Select', class: "button create-button", "data-selection-target": "selectButton", id: "select-button" %>
  </div>
<% end %>

<div>
  <img src="<%= asset_path('test-4.gif') %>" alt="Gif 4" class="gif-level">
</div>

app/views/games/index.html.erb
<% if @games.empty? %>
  <h1 class="choose-language-title mb-4">No game to join yet !</h1>
  <%= link_to "Start Game", games_path(@game), data: { turbo_method: :post }, class: "button create-button mb-5" %>
<% else %>
  <h1 class="choose-language-title mb-4">Choose a game to join !</h1>
  <div class="d-flex flex-wrap justify-content-evenly align-items-center games-wrapper w-100">
    <% @games.each do |game| %>
      <div class="bg-black p-4 my-1" style="width: 45%;">
        <%= link_to avatar_game_path(game), class: "text-decoration-none" do %>
        <div class="d-flex justify-content-between">
          <%= game.name %>
          <div>
            <% game.user_games.each do |user| %>
              <%= image_tag user.avatar, class: "avatar-small ms-2"%>
            <% end %>
          </div>
        </div>
        <div class="d-flex justify-content-between align-items-end">
          <%= image_tag "#{game.language}.png", class: "language-avatar me-3" %>
          <div class="text-white">Level: <%= game.level %></div>
        </div>
        <% end %>
      </div>
    <%end%>
  </div>
<% end %>

app/views/games/show.html.erb
<div data-controller="game" data-game-game-id-value="<%= @game.id %>">
  <%= audio_tag "sound-fight.mp3", id: "game-start-audio" %>
  <% if @game.user_games.count < 2 %>
    <div class="opponent" data-controller="game" data-game-game-id-value="<%= @game.id %>">
      Waiting For Opponent
    </div>

    <%# <div class="ring">Loading
      <span class="wheel"></span>
    </div> %>

    <div class="loader">Searching...</div>


  <% else %>
    <div>
      <% if @game.user_games.find_by(user: current_user).step >= 5 %>
        <%= render "result", game: @game %>
      <% else %>
      <ul data-controller="swap" data-user-game="<%= @user_game.id %>">
        <%= render "question", qcm: @game.qcms[@game.user_games.find_by(user: current_user).step] %>
      </ul>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag %>
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <title>UFCode</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://emoji-css.afeld.me/emoji.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&family=Roboto:wght@100&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
  </head>

  <body>
    <div class="banner" style="background-image: url(<%= asset_path('Background-UFCode.png') %>); height: 100vh; background-size: cover;">
      <div class="container">
        <%= render "shared/navbar" %>
        <%= render "shared/flashes" %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="buttons-container text-center w-100 justify-content-evenly">
  <%= image_tag asset_path('test-1.gif'), alt: "Gif 1", class: "left-gif", id: "test-1" %>
  <div>
    <%= link_to "Start Game", games_path(@game), data: { turbo_method: :post, turbo_frame: "game" }, class: "button create-button mb-5", id: "start-game-button" %>
    <%= link_to "Join Game", games_path, class: "button join-button" %>
  </div>
  <%= image_tag asset_path('test-2.gif'), alt: "Gif 2", class: "right-gif", id: "test-2" %>
</div>

app/views/pages/leaderboard.html.erb
<div class="row mx-auto w-100">
  <div class="col-2 mb-3">RANK</div>
  <div class="col-4 mb-3">PSEUDO</div>
  <div class="col-3 mb-3 text-end">LEVEL</div>
  <div class="col-3 mb-3 text-end">POINTS</div>
  <% rank = 1 %>
  <div class="height-leaderboard">
    <% @users.ranked.each do |user| %>
      <div class="row mb-2">
        <%# RANK %>
        <div class="col-2"><%= rank %></div>
        <%# PSEUDO %>
        <div class="col-4">
          <% if user.user_games.last&.avatar.present? %>
            <%= image_tag user.user_games.last.avatar, class: "avatar-small mx-2" %>
          <% else %>
            <%= image_tag "fighter_avatar.png", class: "avatar-small mx-2" %>
          <% end %>
          <%= user.pseudo %>
        </div>
        <%# LEVEL %>
        <div class="col-3 text-end">
          <%= user.highest_level.nil? ? '-' : user.highest_level %>
        </div>
        <%# POINTS %>
        <div class="col-3 text-end"><%= user.computed_score %></div>
        <% rank += 1  %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/profile.html.erb
<div class= "rejoin d-flex justify-content-center">
  <%= link_to game_path(UserGame.where(user: current_user, game: @games.last).last.game) do  %>
    <div class="btn join-button mt-5 text-decoration: none;">Back To Game</div>
  <% end %>
</div>

  <div class="row mx-auto w-100 d-flex justify-content-center">
    <%# <div class="col-2 mb-3">Past-Game</div> %>
    <div class="col-4 mb-3 text-center  ">Level</div>
    <div class="col-4 mb-3 text-center  ">Win/Lose</div>
    <div class="col-4 mb-3 text-center  ">Points</div>
    <div class="height-leaderboard ">
      <% @games.order(created_at: :desc).each do |game| %>
        <div class="mb-2 d-flex">
          <div class="col-4 text-center">
            <%= game.level %>
          </div>
          <div class="col-4 text-center">
            <%= game.winner == current_user ? 'Win' : 'Lose' %>
          </div>
          <%# POINTS %>
          <div class="col-4 text-center"><%= UserGame.where(game: game, user: current_user).first.score %></div>
        </div>
      <% end %>
    <%# </div> %>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
        <h1 class="title">UFCode</h1>
    <% end %>

    <% if action_name == "show" && controller_name == "games" && @game.user_games.find_by(user: current_user).step < 5 && @game.status == "started" %>
      <div id="timer" data-controller="timer">
      </div>
    <% else %>
      <div class="overflow-hidden">
        <div class="text-white d-flex" id="infinite-scroll-div">
          <% rank = 1 %>
          <% User.all.ranked.each do |user| %>
            <div class="d-flex align-items-center justify-content-center flex-nowrap mx-4" style="white-space: nowrap;"><%= rank %> - <%= user.pseudo %>(<%= user.computed_score %> pts)</div>
            <% rank += 1 %>
          <% end %>
        </div>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to "Leaderboard", leaderboard_path, class: "nav-link white-link me-2" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar2" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "fighter_avatar.png", class: "avatar2", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>


<%# <script>
  let departMinutes = 0
  let temps = departMinutes * 60
  const timerElement = document.getElementById("timer")

  setInterval(() => {
    let minutes = parseInt(temps / 60, 10)
    let secondes = parseInt(temps % 60, 10)

    minutes = minutes < 10 ? "0" + minutes : minutes
    secondes = secondes < 10 ? "0" + secondes : secondes
    if (timerElement) {
      timerElement.innerText = `${minutes}:${secondes}`
      temps = temps + 1
    }

  }, 1000)
</script> %>

app/views/user_games/_avatar.html.erb
<%= image_tag photo, class: 'avatar' %>

app/views/user_games/show.html.erb
<h1 class="user-games-title mt-5 align-items center">Choose a Fighter</h1>
<div class="user-games-form-container mt-4 w-75 mx-auto">
  <%= simple_form_for @user_game, html: { "data-controller": "selection" } do |f| %>
    <%= f.input :avatar,
        as: :radio_buttons,
        legend_tag: false,
        label_method: lambda { |photo| render 'avatar', photo: photo },
        input_html: { class: "tag-selector", required: true, "data-selection-target": "radioButton", "data-action": "click->selection#change" },
        item_wrapper_class: 'tag-item col-2 mx-0 d-flex justify-content-center',
        collection: UserGame::AVATAR_URL %>
    <div class="align-button-center">
      <%= f.submit 'Select', class: "button create-button", "data-selection-target": "selectButton" %>
    </div>
  <% end %>
</div>